services:
  - type: web
    name: quickrss-bpc-proxy
    runtime: image
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
    healthCheckPath: /
    autoDeploy: true
